### ISSUE TITLE
error status code

### ISSUE THREAD

**Issue by chwennnn** [keviiweb/backend#15]
https://github.com/keviiweb/backend/blob/3300c81c788c4a741fda13a52409b482b9343b2b/src/controllers/bookingRequest/approveBookingRequest.controller.js#L120

do we need to provide a status code here? or it will default to 500 if not provided? 
i think the errorFormatter doesnt have a default right, it expects a status code input?

**Comment by fangpinsern** [comment]
if undefined, the error handling middleware will automatically put it as 500. 

But will insert it here to make it consistent
