### ISSUE TITLE
VenueSchema model

### ISSUE THREAD

**Issue by chwennnn** [keviiweb/backend#5]
https://github.com/keviiweb/backend/blob/67c5734fe88c177902041fe682b735d061fc1e65/src/controllers/venue/getAllVenue.controller.js#L23

is venue.image suppose to be in the VenueSchema model?

**Comment by fangpinsern** [comment]
Oh did i miss this out? hahah will add that in. Venue is still in the infant stage. Might be having "subvenues"

**Comment by fangpinsern** [comment]
created PR to fix. Pls check and approve
