### ISSUE TITLE
Get booking response

### ISSUE THREAD

**Issue by chwennnn** [keviiweb/backend#6]
https://github.com/keviiweb/backend/blob/67c5734fe88c177902041fe682b735d061fc1e65/src/controllers/booking/getVenueBookings.controller.js#L46

if dateString does not exist, then set dateString to [timingSlot]? so the response only return timingSlot but no date?

**Comment by fangpinsern** [comment]
no ah. it returns the dateString as a key with the time slot as its value

Example
```
{
    "bookings": {
        "20211026": [
            1,
            2
        ],
        "20211027": [
            1,
            2
        ],
        "20211225": [
            1
        ]
    }
}
```

**Comment by chwennnn** [comment]
ah okay understand liao
