### ISSUE TITLE
isApproved in UserSchema model

### ISSUE THREAD

**Issue by chwennnn** [keviiweb/backend#8]
https://github.com/keviiweb/backend/blob/67c5734fe88c177902041fe682b735d061fc1e65/src/models/user.model.js#L10

why user need isApproved ah?

**Comment by fangpinsern** [comment]
So not anyone can sign up and have an account hahaha

**Comment by chwennnn** [comment]
oh so admin side will be the one approving the account? or need another api for this?
then only if user isApproved is true then can make bookings?
that means must sign up account > get approved first > make bookings > approve bookings ?

**Comment by fangpinsern** [comment]
err yes. so its intended for the user accounts that we are not using ah. So we only want KE residents to be allowed an account mah. so we can do it through this.

BUT

Right now, we are not requiring an account to book. They just need to give us their email

**Comment by chwennnn** [comment]
ah okay 
for now just email works fine 👍
